DECLARE
  PROCEDURE CLEAN_OBJECT(P_OBJECT_TYPE IN VARCHAR2) AS v_temp NUMBER;
  BEGIN
    FOR C_OBJECT IN (SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE=P_OBJECT_TYPE) LOOP
      EXECUTE IMMEDIATE 'DROP '||C_OBJECT.OBJECT_TYPE||' "'||C_OBJECT.OBJECT_NAME||'"';
    END LOOP;
  END CLEAN_OBJECT;
BEGIN
  FOR C IN (SELECT TABLE_NAME, CONSTRAINT_NAME, STATUS, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE='R') LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE "' ||C.TABLE_NAME||'" DROP CONSTRAINT "'||C.CONSTRAINT_NAME||'"';
  END LOOP;
  CLEAN_OBJECT('TRIGGER');
  CLEAN_OBJECT('FUNCTION');
  CLEAN_OBJECT('PROCEDURE');
  CLEAN_OBJECT('SEQUENCE');
  CLEAN_OBJECT('SYNONYM');
  CLEAN_OBJECT('VIEW');
  CLEAN_OBJECT('TABLE');
  CLEAN_OBJECT('INDEX');
  CLEAN_OBJECT('TYPE');
  CLEAN_OBJECT('DATABASE LINK');
END;
/
